version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=licencas
      - DB_USER=root
      - DB_PASS=rootpassword
      - API_HEROSMS=1db85Af88f65e2840754836202520ee6
    depends_on:
      - db

  db:
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: licencas
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/licencas.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
